Gestion.Web/Controllers/PresupuestosEstadosController.cs
using Gestion.Web.Data;
using Gestion.Web.Helpers;
using Gestion.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Gestion.Web.Controllers
{
    [Authorize(Roles = "Admin,PresupuestosEstados")]
    
    public class PresupuestosEstadosController : Controller
    {
        private readonly IPresupuestosEstadosRepository repository; 
        private readonly IUserHelper userHelper;

        public PresupuestosEstadosController(IPresupuestosEstadosRepository repository, IUserHelper userHelper)
        {
            this.repository = repository;
            this.userHelper = userHelper;
        }

        public IActionResult Index()
        {
            return View(repository.GetAll());
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            var PresupuestosEstados = await this.repository.GetByIdAsync(id);
            if (PresupuestosEstados == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            return this.View(PresupuestosEstados);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ParamPresupuestosEstados PresupuestosEstados)
        {
            if (ModelState.IsValid)
            {
                PresupuestosEstados.Estado = true;
                await repository.CreateAsync(PresupuestosEstados);
                return RedirectToAction(nameof(Index));
            }
            return View(PresupuestosEstados);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            var PresupuestosEstados = await this.repository.GetByIdAsync(id);
            if (PresupuestosEstados == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            return this.View(PresupuestosEstados);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, ParamPresupuestosEstados PresupuestosEstados)
        {
            if (id != PresupuestosEstados.Id)
            {
                return new NotFoundViewResult("NoExiste");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await repository.UpdateAsync(PresupuestosEstados);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await repository.ExistAsync(PresupuestosEstados.Id))
                    {
                        return new NotFoundViewResult("NoExiste");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(PresupuestosEstados);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            var PresupuestosEstados = await this.repository.GetByIdAsync(id);
            if (PresupuestosEstados == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            //return this.View(PresupuestosEstados);
            PresupuestosEstados.Estado = !PresupuestosEstados.Estado;
            await repository.DeleteAsync(PresupuestosEstados);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var PresupuestosEstados = await repository.GetByIdAsync(id);
            PresupuestosEstados.Estado = !PresupuestosEstados.Estado;
            await repository.DeleteAsync(PresupuestosEstados);
            return RedirectToAction(nameof(Index));
        }

    }
}

Gestion.Web/Views/PresupuestosEstados/Create.cshtml
@model Gestion.Web.Models.ParamPresupuestosEstados

@{
    ViewData["Title"] = "Nuevo Estado";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Sistema de gestíon
            <small>Gestion de Presupuestos</small>
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home"><i class="fas fa-tachometer-alt"></i> Inicio</a></li>
            <li><a asp-controller="Clientes">Listado de Estados</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ficha del Estado</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div class="box-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Codigo" class="control-label"></label>
                                <input asp-for="Codigo" class="form-control input-sm" />
                                <span asp-validation-for="Codigo" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Descripcion" class="control-label"></label>
                                <input asp-for="Descripcion" class="form-control input-sm" />
                                <span asp-validation-for="Descripcion" class="text-danger"></span>
                            </div>
                            
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <input type="submit" value="Guardar" class="btn btn-primary" />
                            <a asp-action="Index" class="btn btn-default pull-right">Volver al Listado</a>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
            <!--/.col-->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gestion.Web/Views/PresupuestosEstados/Details.cshtml
@model Gestion.Web.Models.ParamPresupuestosEstados

@{
    ViewData["Title"] = "Detalle del Estado";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Sistema de gestíon
            <small>Gestion de Presupuestos</small>
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Inicio</a></li>
            <li><a asp-controller="PresupuestosEstados" asp-action="Index">Listado de Estados</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Datos del Estado</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div class="box-body">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Codigo)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Codigo)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Descripcion)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Descripcion)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Estado)
                                </dt>
                                <dd>
                                    @{
                                        if (Model.Estado)
                                        {
                                            <span class="label label-success">Activo</span>
                                        }
                                        else
                                        {
                                            <span class="label label-danger">Inactivo</span>
                                        }

                                    }
                                </dd>
                            </dl>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Editar datos del Estado</a>
                            <a asp-action="Index" class="btn btn-default pull-right">Volver al Listado</a>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
            <!--/.col-->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gestion.Web/Views/PresupuestosEstados/Edit.cshtml
@model Gestion.Web.Models.ParamPresupuestosEstados

@{
    ViewData["Title"] = "Editar Estado";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Sistema de gestíon
            <small>Gestion de Presupuestos</small>
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Inicio</a></li>
            <li><a asp-controller="PresupuestosEstados" asp-action="Index">Listado de Estados</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ficha del Estado</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form asp-action="Edit" enctype="multipart/form-data">
                        <div class="box-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <input type="hidden" asp-for="Estado" />

                            <div class="form-group">
                                <label asp-for="Codigo" class="control-label"></label>
                                <input asp-for="Codigo" class="form-control" />
                                <span asp-validation-for="Codigo" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Descripcion" class="control-label"></label>
                                <input asp-for="Descripcion" class="form-control input-sm" />
                                <span asp-validation-for="Descripcion" class="text-danger"></span>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <input type="submit" value="Guardar" class="btn btn-primary" />
                            <a asp-action="Index" class="btn btn-default pull-right">Volver al Listado</a>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
            <!--/.col-->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gestion.Web/Views/PresupuestosEstados/Index.cshtml
@model IEnumerable<Gestion.Web.Models.ParamPresupuestosEstados>

@{
    ViewData["Title"] = "Listado de Estados";
}

<!--================================
BREADCRUMB
=================================-->
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Sistema de gestíon <small>Gestion de Presupuestos</small>
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home"><i class="fas fa-tachometer-alt"></i> Inicio</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>
    <!--================================
        CONTENIDO
    =================================-->
    <section class="content">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">@ViewData["Title"]</h3>
                <p><a asp-action="Create" class="btn btn-primary btn-sm pull-right" aria-hidden="true">Nuevo Estado</a></p>
            </div>
            <div class="box-body">
                <p>

                </p>
                <table id="dTable" class="table dt-responsive table-condensed table-bordered table-striped" width="100%">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Codigo)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Descripcion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Estado)
                            </th>
                            <th>Operaciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Codigo)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Descripcion)
                                </td>                                
                                <td>
                                    @Html.DisplayFor(modelItem => item.Estado)
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-pen"></i></a>
                                        <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id"><i class="fa fa-search-plus"></i></a>
                                        <button data-id="@item.Id" class="btn btn-danger deleteItem" data-toggle="modal" data-target="#deleteDialog"><i class="fa fa-trash"></i></button>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>            
        </div>
    </section>
</div>


<div id="deleteDialog" class="modal fade">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Delete</h4>
                <button type="button" class="close" data-dismiss="modal"><i class="fa fa-window-close"></i></button>
            </div>
            <div class="modal-body">
                <p>¿Quieres borrar el Estado?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" id="btnYesDelete">Delete</button>
                <button type="button" class="btn btn-success" id="btnNoDelete">No</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        $(document).ready(function () {

            var item_to_delete;

            $('.deleteItem').click((e) => {
                item_to_delete = e.currentTarget.dataset.id;
            });

            $("#btnYesDelete").click(function () {
                window.location.href = '/PresupuestosEstados/Delete/' + item_to_delete;
            });


            $('#dTable').DataTable({
                "processing": "true",
                "retrieve": "true",
                "language": {
                    "processing": "Procesando... Espere por favor",
                    "lengthMenu": "Mostrar _MENU_ registros por pagina",
                    "zeroRecords": "Nada encontrado",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "No hay registros disponibles",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sSearch": "Buscar:",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    }
                }
            });
        });

    </script>
}

Gestion.Web/Views/PresupuestosEstados/NoExiste.cshtml
@{
    ViewData["Title"] = "El Estado no Existe";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            404 @ViewData["Title"]
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home"><i class="fa fa-dashboard"></i> Inicio</a></li>
            <li><a asp-controller="PresupuestosEstados">Presupuestos Estado</a></li>
            <li class="active">404 Error</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="error-page">
            <h2 class="headline text-yellow"> 404</h2>

            <div class="error-content">
                <p><i class="fa fa-warning text-yellow"></i></p>

                <p>
                    @ViewData["Title"]
                </p>

            </div>
            <!-- /.error-content -->
        </div>
        <!-- /.error-page -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->