Gestion.Web/Controllers/CuentasVentasController.cs
using Gestion.Web.Data;
using Gestion.Web.Helpers;
using Gestion.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Gestion.Web.Controllers
{
    [Authorize(Roles = "Admin,CuentasVentas")]
    
    public class CuentasVentasController : Controller
    {
        private readonly ICuentasVentasRepository repository; 
        private readonly IUserHelper userHelper;

        public CuentasVentasController(ICuentasVentasRepository repository, IUserHelper userHelper)
        {
            this.repository = repository;
            this.userHelper = userHelper;
        }

        public IActionResult Index()
        {
            return View(repository.GetAll());
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            var CuentasVentas = await this.repository.GetByIdAsync(id);
            if (CuentasVentas == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            return this.View(CuentasVentas);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ParamCuentasVentas CuentasVentas)
        {
            if (ModelState.IsValid)
            {
                CuentasVentas.Estado = true;
                await repository.CreateAsync(CuentasVentas);
                return RedirectToAction(nameof(Index));
            }
            return View(CuentasVentas);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            var CuentasVentas = await this.repository.GetByIdAsync(id);
            if (CuentasVentas == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            return this.View(CuentasVentas);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, ParamCuentasVentas CuentasVentas)
        {
            if (id != CuentasVentas.Id)
            {
                return new NotFoundViewResult("NoExiste");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await repository.UpdateAsync(CuentasVentas);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await repository.ExistAsync(CuentasVentas.Id))
                    {
                        return new NotFoundViewResult("NoExiste");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(CuentasVentas);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            var CuentasVentas = await this.repository.GetByIdAsync(id);
            if (CuentasVentas == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            CuentasVentas.Estado = !CuentasVentas.Estado;
            await repository.DeleteAsync(CuentasVentas);
            return RedirectToAction(nameof(Index));
        }        

    }
}

Gestion.Web/Views/CuentasVentas/Create.cshtml
@model Gestion.Web.Models.ParamCuentasVentas

@{
    ViewData["Title"] = "Nuevo Cuenta Venta";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Sistema de gestíon
            <small>Gestion de Clientes</small>
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Inicio</a></li>
            <li><a asp-controller="CuentasVentas" asp-action="Index">Listado de Cuentas Ventas</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ficha del Cuenta Venta</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div class="box-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Codigo" class="control-label"></label>
                                <input asp-for="Codigo" class="form-control input-sm" />
                                <span asp-validation-for="Codigo" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Descripcion" class="control-label"></label>
                                <input asp-for="Descripcion" class="form-control input-sm" />
                                <span asp-validation-for="Descripcion" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label>
                                    <input asp-for="Defecto" type="checkbox" class="minimal">
                                    <label asp-for="Defecto" class="control-label"></label>
                                </label>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <input type="submit" value="Guardar" class="btn btn-primary" />
                            <a asp-action="Index" class="btn btn-default pull-right">Volver al Listado</a>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
            <!--/.col-->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gestion.Web/Views/CuentasVentas/Details.cshtml
@model Gestion.Web.Models.ParamCuentasVentas

@{
    ViewData["Title"] = "Detalle del Cuenta Venta";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Sistema de gestíon
            <small>Gestion de Clientes</small>
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Inicio</a></li>
            <li><a asp-controller="CuentasVentas" asp-action="Index">Listado de Cuentas Ventas</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Datos del Cuenta Venta</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div class="box-body">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Codigo)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Codigo)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Descripcion)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Descripcion)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Defecto)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Defecto)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Estado)
                                </dt>
                                <dd>
                                    @{
                                        if (Model.Estado)
                                        {
                                            <span class="label label-success">Activo</span>
                                        }
                                        else
                                        {
                                            <span class="label label-danger">Inactivo</span>
                                        }

                                    }
                                </dd>
                            </dl>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Editar datos del Cuenta Venta</a>
                            <a asp-action="Index" class="btn btn-default pull-right">Volver al Listado</a>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
            <!--/.col-->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gestion.Web/Views/CuentasVentas/Edit.cshtml
@model Gestion.Web.Models.ParamCuentasVentas

@{
    ViewData["Title"] = "Editar Cuenta Venta";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Sistema de gestíon
            <small>Gestion de Clientes</small>
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Inicio</a></li>
            <li><a asp-controller="CuentasVentas" asp-action="Index">Listado de Cuentas Ventas</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ficha del Cuenta Venta</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form asp-action="Edit" enctype="multipart/form-data">
                        <div class="box-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" /> 
                            <input type="hidden" asp-for="Estado" />

                            <div class="form-group">
                                <label asp-for="Codigo" class="control-label"></label>
                                <input asp-for="Codigo" class="form-control" />
                                <span asp-validation-for="Codigo" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Descripcion" class="control-label"></label>
                                <input asp-for="Descripcion" class="form-control input-sm" />
                                <span asp-validation-for="Descripcion" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label>
                                    <input asp-for="Defecto" type="checkbox" class="minimal">
                                    <label asp-for="Defecto" class="control-label"></label>
                                </label>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <input type="submit" value="Guardar" class="btn btn-primary" />
                            <a asp-action="Index" class="btn btn-default pull-right">Volver al Listado</a>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
            <!--/.col-->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gestion.Web/Views/CuentasVentas/Index.cshtml
@model IEnumerable<Gestion.Web.Models.ParamCuentasVentas>

@{
    ViewData["Title"] = "Listado de Cuentas Ventas";
}

<!--================================
BREADCRUMB
=================================-->
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Sistema de gestíon <small>Gestion de Ajustes</small>
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Inicio</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>
    <!--================================
        CONTENIDO
    =================================-->
    <section class="content">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">@ViewData["Title"]</h3>
                <p><a asp-action="Create" class="btn btn-primary btn-sm pull-right" aria-hidden="true">Nuevo Cuenta</a></p>
            </div>
            <div class="box-body">
                <p>

                </p>
                <table id="dTable" class="table dt-responsive table-condensed table-bordered table-striped" width="100%">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Codigo)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Descripcion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Defecto)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Estado)
                            </th>
                            <th>Operaciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Codigo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Descripcion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Defecto)
                            </td>
                            <td>
                                @{
                                    if (item.Estado)
                                    {
                                        <span class="label label-success">Activo</span>
                                    }
                                    else
                                    {
                                        <span class="label label-danger">Inactivo</span>
                                    }

                                }


                            </td>
                            <td>
                                <div class="btn-group">
                                    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-pen"></i></a>
                                    <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id"><i class="fa fa-search-plus"></i></a>
                                    @{
                                        if (item.Estado)
                                        {
                                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id"><i class="glyphicon glyphicon-remove"></i></a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-success" asp-action="Delete" asp-route-id="@item.Id"><i class="glyphicon glyphicon-ok"></i></a>
                                        }

                                    }
                                </div>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>            
        </div>
    </section>
</div>


@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        $(document).ready(function () {

            $('#dTable').DataTable({
                "processing": "true",
                "retrieve": "true",
                "language": {
                    "processing": "Procesando... Espere por favor",
                    "lengthMenu": "Mostrar _MENU_ registros por pagina",
                    "zeroRecords": "Nada encontrado",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "No hay registros disponibles",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sSearch": "Buscar:",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    }
                }
            });
        });

    </script>
}

Gestion.Web/Views/CuentasVentas/NoExiste.cshtml
@{
    ViewData["Title"] = "El Cuenta Venta no Existe";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            404 @ViewData["Title"]
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home" asp-action="Index"><i class="fa fa-dashboard"></i> Inicio</a></li>
            <li><a asp-controller="CuentasVentas" asp-action="Index">Cuentas Ventas</a></li>
            <li class="active">404 Error</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="error-page">
            <h2 class="headline text-yellow"> 404</h2>

            <div class="error-content">
                <p><i class="fa fa-warning text-yellow"></i></p>

                <p>
                    @ViewData["Title"]
                </p>

            </div>
            <!-- /.error-content -->
        </div>
        <!-- /.error-page -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->