Gestion.Web/Models/FormasPagosCotizacion.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Gestion.Web.Models
{
    public partial class FormasPagosCotizacion : IEntidades
    {
        public string Id { get; set; }

        [DisplayFormat(DataFormatString = "{0:C2}")]
        [Required(ErrorMessage = "El campo {0} es obligatorio.")]
        public decimal Cotizacion { get; set; }

        [DataType(DataType.Date, ErrorMessage = "El formato de la fecha no es valido")]
        [Display(Name = "Vigencia Desde")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? FechaDesde { get; set; }
        [DataType(DataType.Date, ErrorMessage = "El formato de la fecha no es valido")]
        [Display(Name = "Vigencia Hasta")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime? FechaHasta { get; set; }
        public bool Estado { get; set; }    
    }
}

Gestion.Web/Controllers/FormasPagosCotizacionController.cs
using Gestion.Web.Data;
using Gestion.Web.Helpers;
using Gestion.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading.Tasks;

namespace Gestion.Web.Controllers
{
    [Authorize(Roles = "Admin,FormasPagosCotizacion")]
    public class FormasPagosCotizacionController : Controller
    {
        private readonly IFormasPagosCotizacionRepository repository; 
        private readonly IUserHelper userHelper;
        private readonly IFormasPagosCotizacionRepository cuotasRepository;
        private readonly IEntidadesRepository entidadesRepository;

        public FormasPagosCotizacionController(IFormasPagosCotizacionRepository repository, 
            IUserHelper userHelper,
            IFormasPagosCotizacionRepository cuotasRepository,
            IEntidadesRepository entidadesRepository
            )
        {
            this.repository = repository;
            this.userHelper = userHelper;
            this.cuotasRepository = cuotasRepository;
            this.entidadesRepository = entidadesRepository;
        }

        public IActionResult Index()
        {
            return View(repository.GetAll());
        }

        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            var FormasPagosCotizacion = await this.repository.GetByIdAsync(id);
            if (FormasPagosCotizacion == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            return this.View(FormasPagosCotizacion);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FormasPagosCotizacion FormasPagosCotizacion)
        {
            if (ModelState.IsValid)
            {
                FormasPagosCotizacion.Estado = true;
                await repository.CreateAsync(FormasPagosCotizacion);
                return RedirectToAction(nameof(Index));
            }

            return View(FormasPagosCotizacion);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            var FormasPagosCotizacion = await this.repository.GetByIdAsync(id);
            if (FormasPagosCotizacion == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            return this.View(FormasPagosCotizacion);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, FormasPagosCotizacion FormasPagosCotizacion)
        {
            if (id != FormasPagosCotizacion.Id)
            {
                return new NotFoundViewResult("NoExiste");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await repository.UpdateAsync(FormasPagosCotizacion);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await repository.ExistAsync(FormasPagosCotizacion.Id))
                    {
                        return new NotFoundViewResult("NoExiste");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(FormasPagosCotizacion);
        }

        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            var FormasPagosCotizacion = await this.repository.GetByIdAsync(id);
            if (FormasPagosCotizacion == null)
            {
                return new NotFoundViewResult("NoExiste");
            }

            FormasPagosCotizacion.Estado = !FormasPagosCotizacion.Estado;
            await repository.DeleteAsync(FormasPagosCotizacion);
            return RedirectToAction(nameof(Index));
        }

    }
}

Gestion.Web/Views/FormasPagosCotizacion/Create.cshtml
@model Gestion.Web.Models.FormasPagosCotizacion
@{
    ViewData["Title"] = "Nueva Cotizacion";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Sistema de gestíon
            <small>Formas de Pagos</small>
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Inicio</a></li>
            <li><a asp-controller="FormasPagosCotizacion" asp-action="Index">Listado de Cotizaciones</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ficha de la Cotizacion</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div class="box-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <label asp-for="Cotizacion" class="control-label"></label>
                                <input asp-for="Cotizacion" class="form-control" />
                                <span asp-validation-for="Cotizacion" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="FechaDesde" class="control-label"></label>
                                <input asp-for="FechaDesde" type="date" class="form-control input-sm" />
                                <span asp-validation-for="FechaDesde" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="FechaHasta" class="control-label"></label>
                                <input asp-for="FechaHasta" type="date" class="form-control input-sm" />
                                <span asp-validation-for="FechaHasta" class="text-danger"></span>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <input type="submit" value="Guardar" class="btn btn-primary" />
                            <a asp-action="Index" class="btn btn-default pull-right">Volver al Listado</a>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
            <!--/.col-->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gestion.Web/Views/FormasPagosCotizacion/Details.cshtml
@model Gestion.Web.Models.FormasPagosCotizacion

@{
    ViewData["Title"] = "Detalle de la Cotizacion";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Sistema de gestíon
            <small>Formas de Pagos</small>
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Inicio</a></li>
            <li><a asp-controller="FormasPagosCotizacion" asp-action="Index">Listado de Cotizaciones</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Datos de la Cotizacion</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div class="box-body">
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Cotizacion)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.Cotizacion)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.FechaDesde)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.FechaDesde)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.FechaHasta)
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.FechaHasta)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Estado)
                                </dt>
                                <dd>
                                    @{
                                        if (Model.Estado)
                                        {
                                            <span class="label label-success">Activo</span>
                                        }
                                        else
                                        {
                                            <span class="label label-danger">Inactivo</span>
                                        }

                                    }
                                </dd>
                            </dl>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Editar datos de la Entidad</a>
                            <a asp-action="Index" class="btn btn-default pull-right">Volver al Listado</a>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
            <!--/.col-->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gestion.Web/Views/FormasPagosCotizacion/Edit.cshtml
@model Gestion.Web.Models.FormasPagosCotizacion

@{
    ViewData["Title"] = "Editar Cotizacion";
}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Sistema de gestíon
            <small>Formas Pagos</small>
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Inicio</a></li>
            <li><a asp-controller="FormasPagosCotizacion" asp-action="Index">Listado de Cotizaciones</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Ficha de la Cotizacion</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form asp-action="Edit" enctype="multipart/form-data">
                        <div class="box-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <input type="hidden" asp-for="Estado" />

                            <div class="form-group">
                                <label asp-for="Cotizacion" class="control-label"></label>
                                <input asp-for="Cotizacion" class="form-control" />
                                <span asp-validation-for="Cotizacion" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="FechaDesde" class="control-label"></label>
                                <input asp-for="FechaDesde" type="date" class="form-control input-sm" />
                                <span asp-validation-for="FechaDesde" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="FechaHasta" class="control-label"></label>
                                <input asp-for="FechaHasta" type="date" class="form-control input-sm" />
                                <span asp-validation-for="FechaHasta" class="text-danger"></span>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <input type="submit" value="Guardar" class="btn btn-primary" />
                            <a asp-action="Index" class="btn btn-default pull-right">Volver al Listado</a>
                        </div>
                    </form>
                </div>
                <!-- /.box -->
            </div>
            <!--/.col-->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gestion.Web/Views/FormasPagosCotizacion/Index.cshtml
@model IEnumerable<Gestion.Web.Models.FormasPagosCotizacion>

@{
    ViewData["Title"] = "Listado de Cotizaciones";
}

<!--================================
BREADCRUMB
=================================-->
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Sistema de gestíon <small>Formas de Pagos</small>
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home" asp-action="Index"><i class="fas fa-tachometer-alt"></i> Inicio</a></li>
            <li class="active">@ViewData["Title"]</li>
        </ol>
    </section>
    <!--================================
        CONTENIDO
    =================================-->
    <section class="content">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">@ViewData["Title"]</h3>
                <p><a asp-action="Create" class="btn btn-primary btn-sm pull-right" aria-hidden="true">Nueva Cotizacion</a></p>
            </div>
            <div class="box-body">
                <p>

                </p>
                <table id="dTable" class="table dt-responsive table-condensed table-bordered table-striped" width="100%">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Cotizacion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FechaDesde)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FechaHasta)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Estado)
                            </th>
                            <th>Operaciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cotizacion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaDesde)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaHasta)
                            </td>
                            <td>
                                @{
                                    if (item.Estado)
                                    {
                                        <span class="label label-success">Activo</span>
                                    }
                                    else
                                    {
                                        <span class="label label-danger">Inactivo</span>
                                    }

                                }



                            <td>
                                <div class="btn-group">
                                    <a class="btn btn-warning" asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-pen"></i></a>
                                    <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id"><i class="fa fa-search-plus"></i></a>
                                    @{
                                        if (item.Estado)
                                        {
                                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id"><i class="glyphicon glyphicon-remove"></i></a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-success" asp-action="Delete" asp-route-id="@item.Id"><i class="glyphicon glyphicon-ok"></i></a>
                                        }

                                    }
                                </div>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>            
        </div>
    </section>
</div>


@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        $(document).ready(function () {

            $('#dTable').DataTable({
                "processing": "true",
                "retrieve": "true",
                "language": {
                    "processing": "Procesando... Espere por favor",
                    "lengthMenu": "Mostrar _MENU_ registros por pagina",
                    "zeroRecords": "Nada encontrado",
                    "info": "Mostrando página _PAGE_ de _PAGES_",
                    "infoEmpty": "No hay registros disponibles",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sSearch": "Buscar:",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    }
                }
            });
        });

    </script>
}

Gestion.Web/Views/FormasPagosCotizacion/NoExiste.cshtml
@{
    ViewData["Title"] = "La Cotizacion no Existe";
}

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            404 @ViewData["Title"]
        </h1>
        <ol class="breadcrumb">
            <li><a asp-controller="Home" asp-action="Index"><i class="fa fa-dashboard"></i> Inicio</a></li>
            <li><a asp-controller="FormasPagosCotizacion" asp-action="Index">Cotizaciones</a></li>
            <li class="active">404 Error</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="error-page">
            <h2 class="headline text-yellow"> 404</h2>

            <div class="error-content">
                <p><i class="fa fa-warning text-yellow"></i></p>

                <p>
                    @ViewData["Title"]
                </p>

            </div>
            <!-- /.error-content -->
        </div>
        <!-- /.error-page -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->